### ISSUE TITLE
Feedback for python - Reload with SSH keys

### ISSUE THREAD

**Issue by takara9** [softlayer/softlayer.github.io#102]
Feedback regarding: https://softlayer.github.io/python/reload_hardware/

imageTemplateId in config parameter does not work, 
OS image is not changed by this parameter.

        config = {
            'imageTemplateId': imageId, 
            'sshKeyIds': [sshKey1, sshKey2]
        }

It should be in following.

	config = {
            'sshKeyIds': [sshKey1, sshKey2],
            'itemPrices': [{'id': priceId}]
	}

**Comment by acamacho82** [comment]
I tested the example and I was able to reload using the [imageTemplateId](https://softlayer.github.io/reference/datatypes/SoftLayer_Container_Hardware_Server_Configuration/#imageTemplateId) property, the imageId provided needs to be a Flex image. Anyway I will update the document in order to let readers know that it is required to used a flex image id

**Comment by allmightyspiff** [comment]
That page has now been updated with a few other reload examples that might help. Along with the (now depreciated) flex image examples, there is one that includes using itemPrices.
