### ISSUE TITLE
Feedback for go - get_unattached_portal_storages.go

### ISSUE THREAD

**Issue by bennythejudge** [softlayer/softlayer.github.io#131]
Feedback regarding: https://softlayer.github.io/go/get_unattached_portal_storages.go/

I am trying this and I am getting:

```
 go run get_unattached_portal_storages.go

 Unable to retrieve Portable Storages:
 - SOAP-ENV:Client: Bad Request (HTTP 200)
```

I made a tiny modification:

```
/*
Get unattached portal storages.

The script gets all unattached portal storages in the account.

Important manual pages:
http://sldn.softlayer.com/reference/services/SoftLayer_Account
http://sldn.softlayer.com/reference/services/SoftLayer_Account/getPortableStorageVolumes
http://sldn.softlayer.com/reference/datatypes/SoftLayer_Virtual_Disk_Image

@License: http://sldn.softlayer.com/article/License
@Author: SoftLayer Technologies, Inc. <sldn@softlayer.com>
*/

package main

import (
    "os"
    "fmt"
    "github.com/softlayer/softlayer-go/datatypes"
    "github.com/softlayer/softlayer-go/services"
    "github.com/softlayer/softlayer-go/session"
    "encoding/json"
)

func main() {
    // SoftLayer API username and key
    // username := "set me"
    // apikey   := "set me"
    username      := os.Getenv("SL_USERNAME")
    apikey        := os.Getenv("SL_APIKEY")

    // Create a session
    sess := session.New(username, apikey)

    // Get SoftLayer_Account service
    service := services.GetAccountService(sess)

    // Use masks in order to get Guests of StorageRepositories
    mask := "storageRepository[guests]"

    // All unattached storage objects will be saved here.
    unattachedStorages := []datatypes.Virtual_Disk_Image {}

    // Get all portable storage volumes
    portableStorages, err := service.Mask(mask).GetPortableStorageVolumes()
    if err != nil {
        fmt.Printf("\n Unable to retrieve Portable Storages:\n - %s\n", err)
        return
    }

    // Search and save all unattached storages
    for _,storage := range portableStorages {
        if storage.StorageRepository != nil {
                if len(storage.StorageRepository.Guests) == 0 {
                unattachedStorages = append(unattachedStorages, storage)
                }
            }
    }

    // Following helps to print the result in json format.
    for _,storage := range unattachedStorages {
        jsonFormat, jsonErr := json.Marshal(storage)
        if jsonErr != nil {
            fmt.Println(jsonErr)
            return
        }

        fmt.Println(string(jsonFormat))
    }
} 
```

The error is confusing (HTTP 200 and error?)

**Comment by acamacho82** [comment]
I was able to reproduce the error, it happens when using XMLRPC instead of REST endpoint, the softlayer-go client uses REST by default unless you have xmlrpc configured in your **~/.softlayer** file, so I recommend you to update the **~/.softlayer**  or add the following code line:

`sess.Endpoint = "https://api.softlayer.com/rest/v3"`

**Comment by acamacho82** [comment]
Researching, I realized the client builds a _Legacy Object Mask_ structure when working with xmlrpc but the mask of example above is for _Extended Object Mask_, so I think  that is the reason why the server return the error **"SOAP-ENV:Client: Bad Request"**.

I debugged the code by adding `sess.Debug = true`  and the client creates the following xml structure when `mask := "storageRepository[guests]"` is set:

```xml
<member>
  <name>SoftLayer_AccountObjectMask</name>
  <value>
	<struct>
	  <member>
		<name>mask</name>
		<value>
		  <struct>
			<member>
			  <name>mask[storageRepository[guests]]</name>
			  <value>
				<array>
				  <data/>
				</array>
			  </value>
			</member>
		  </struct>
		</value>
	  </member>
	</struct>
  </value>
</member>
```

According to https://softlayer.github.io/article/xml-rpc/ the previous xml is not the correct. To make the client builds an structure such as in the article, it must be used dot **.** instead of **[]**.

`mask := "storageRepository.guests"`

```xml
<member>
  <name>SoftLayer_AccountObjectMask</name>
  <value>
	<struct>
	  <member>
		<name>mask</name>
		<value>
		  <struct>
		    <member>
			  <name>storageRepository</name>
			  <value>
				<struct>
				  <member>
					<name>guests</name>
					<value>
					  <array>
						<data/>
					  </array>
					</value>
				  </member>
				</struct>
			  </value>
			</member>
		  </struct>
		</value>
	  </member>
	</struct>
  </value>
</member>
```

Although, the previous structure is correct, the obtained response doesn't have `storageRepository.guests` data information, this could be an issue from server side so it is recommended to use REST endpoint instead, specially if working with masks.

**Comment by bennythejudge** [comment]
I checked and it's true, my `~/.softlayer` contains an endpoint 
```endpoint_url = https://api.softlayer.com/xmlrpc/v3/```

Considering that I didn't know this file and I did not create it, the questions are: 
what created it? 
what is using it?

I will try to enter your suggested entry and see what breaks.

**Comment by acamacho82** [comment]
Check if you have the `slcli` in your environment:

`$ slcli --version`

if you have it installed then it could be that at some point someone have configured this tool through `slcli setup`. 

See: 
https://softlayer-python.readthedocs.io/en/latest/cli.html#configuration-setup
https://softlayer-python.readthedocs.io/en/latest/config_file.html#config-file

**Comment by allmightyspiff** [comment]
Sounds like switching your endpoint to use the REST should work, but if that doesn't fix the issue let us know.
