### ISSUE TITLE
Feedback for python - Manage Users

### ISSUE THREAD

**Issue by owhc** [softlayer/softlayer.github.io#97]
Feedback regarding: https://softlayer.github.io/python/manageUsers/
How can I create an user with VPN ONLY and allow all Devices access? Would you please advise me which API I can implement those processes? Thank you.

**Comment by allmightyspiff** [comment]
Sorry this took so long to get around to updating...

When creating a user, use the VPN_ONLY status instead of the Active Status.

```
$ slcli call-api SoftLayer_User_Customer_Status getAllObjects
1001  ACTIVE          Active
1002  DISABLED        Disabled
1003  INACTIVE        Inactive
1004  PENDING         Pending
1021  CANCEL_PENDING  cancel_pending
1022  VPN_ONLY        VPN Only
```

ALL hardware access is a permission. 
```
$ slcli user  permissions sl307608-chgallo  | grep -i hardware
All Hardware Access                        ACCESS_ALL_HARDWARE                          True
```

Otherwise you need to use https://softlayer.github.io/reference/services/SoftLayer_User_Customer/addHardwareAccess/ to give access to specific hardware.
